name: pitstop_frontend
description: "A Zomato-style Flutter frontend for the PitStop app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

# -------------------------------------------------
# 🧱 DEPENDENCIES
# -------------------------------------------------
dependencies:
  flutter:
    sdk: flutter

  # --- STATE MANAGEMENT ---
  provider: ^6.1.5+1

  # --- FIREBASE & AUTH ---
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

  # --- UI & VISUALS ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.1.1
  fl_chart: ^1.1.1

  # --- MAPS & LOCATION ---
  google_maps_flutter: ^2.7.0
  location: ^8.0.1
  flutter_polyline_points: ^3.1.0

  # --- UTILITIES ---
  url_launcher: ^6.3.2

# -------------------------------------------------
# 🧰 DEVELOPMENT DEPENDENCIES
# -------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# -------------------------------------------------
# 🎨 FLUTTER CONFIGURATION
# -------------------------------------------------
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
        - asset: lib/assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700

# -------------------------------------------------
# 🪞 APP ICON GENERATION
# -------------------------------------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/app_icon.png"
  remove_alpha_ios: true