name: pitstop_frontend
description: "A Flutter frontend for the PitStop roadside assistance app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

# -------------------------------------------------
# 🧱 DEPENDENCIES
# -------------------------------------------------
dependencies:
  flutter:
    sdk: flutter

  # --- CORE & STATE MANAGEMENT ---
  provider: ^6.1.2

  # --- FIREBASE & AUTH (Compatible Set) ---
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0

  # --- UI & VISUALS ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^4.2.1
  fl_chart: ^0.68.0
  
  # --- MAPS & LOCATION ---
  google_maps_flutter: ^2.7.0
  location: ^6.0.2
  flutter_polyline_points: ^2.0.0

  # --- UTILITIES ---
  url_launcher: ^6.3.0


# -------------------------------------------------
# 🧰 DEVELOPMENT DEPENDENCIES
# -------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

# -------------------------------------------------
# 🎨 FLUTTER CONFIGURATION
# -------------------------------------------------
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
        - asset: lib/assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700

# -------------------------------------------------
# 🪞 APP ICON GENERATION
# -------------------------------------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/app_icon.png"
  remove_alpha_ios: true