name: pitstop_frontend
description: "A Zomato-style Flutter frontend for PitStop app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

# Dependencies (sorted alphabetically for clarity)
dependencies:
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Asset folders (all files under these dirs will be bundled automatically)
  assets:
    - lib/assets/images/
    - lib/assets/fonts/

  # Font definitions for Roboto
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
        - asset: lib/assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700